### ISSUE TITLE
Problem with the number of digits on the cell phone

### ISSUE THREAD

**Issue by gelylyne** [ong-bitcoin-argentina/DIDI-SSI-Mobile#126]
Please help, that I can't create an account.

The phone format (Sign-up) only allows 10 digits for the phone number. 
But in my country the phones have 9 digits (+51 xxx xxx xxx) and other countries 8 digits.

The restriction of the digits, I think it is in the next line:
[https://github.com/ong-bitcoin-argentina/DIDI-SSI-Mobile/blob/71d2d527aa225d415b81f747ab3a51aeee0bc719/src/src/model/Validations.tsx#L62](https://github.com/ong-bitcoin-argentina/DIDI-SSI-Mobile/blob/71d2d527aa225d415b81f747ab3a51aeee0bc719/src/src/model/Validations.tsx#L62)

The next page with the formats of different countries
http://chartsbin.com/view/zg0

**Comment by MatiasOS** [comment]
Fixed in https://github.com/ong-bitcoin-argentina/DIDI-SSI-Mobile/pull/127 y https://github.com/ong-bitcoin-argentina/DIDI-SSI-Server/pull/155
